### ISSUE TITLE
Problem with fonts not loading

### ISSUE THREAD

**Issue by mdamien** [medialab/medialab.sciences-po.fr#12]
## Screenshot

<hr>

![image](https://user-images.githubusercontent.com/1469823/45035867-52a72b80-b05b-11e8-9820-cac40562b35b.png)

(the menu font is not loaded correctly)

</hr>

## Explanation

Looks like it's because we try to load fonts via http when the site is https:

```
	<link href='http://fonts.googleapis.com/css?family=Bitter:400,700,400italic' rel='stylesheet' type='text/css'>
```

But looks like it was fixed:

https://github.com/medialab/medialab.sciences-po.fr/blob/6be6accb8e9f642ab1e2fb7f2a6c0430a4264a02/wp-content/themes/medialab_v5/header.php#L53-L58

**Comment by boogheta** [comment]
fixed manually in the admin editor since it's already fixed in the code (not sure how to rsync the latest version myself, cc @robindemourat @paulgirard )
